let mhealth = [
    'Average Number Of Mentally Unhealthy Days',
    'Mental Health Provider Rate',
    'Number Mental Health Providers',
    'Percent Frequent Mental Distress'
];
let topcats = [
    'Average Number Of Physically Unhealthy Days',
    'Median Household Income',
    'Per Capita Income',
    'Percent Below Poverty',
    'Percent Fair Or Poor Health',
    'Percent Frequent Physical Distress',
    'Percent Smokers',
    'Percentile Rank Below Poverty',
    'Percentile Rank No Highschool Diploma',
    'Percentile Rank Per Capita Income',
    'Percentile Rank Social Vulnerability'
];
let nc = [
    'Fips',
    'State',
    'County',
    'Lat',
    'Lon'
];
let others = [
    'Age Adjusted Death Rate',
    'Annual Average Violent Crimes',
    'Area Sqmi',
    'Average Daily Pm2 5',
    'Average Grade Performance',
    'Average Grade Performance 2',
    'Average Traffic Volume Per Meter Of Major Roadways',
    'Child Mortality Rate',
    'Chlamydia Rate',
    'Dentist Rate',
    'Drug Overdose Mortality Rate',
    'Eightieth Percentile Income',
    'Firearm Fatalities Rate',
    'Food Environment Index',
    'High School Graduation Rate',
    'Homicide Rate',
    'Inadequate Facilities',
    'Income Ratio',
    'Infant Mortality Rate',
    'Injury Death Rate',
    'Juvenile Arrest Rate',
    'Labor Force',
    'Life Expectancy',
    'Motor Vehicle Mortality Rate',
    'Number Age 17 And Younger',
    'Number Age 65 And Older',
    'Number Alcohol Impaired Driving Deaths',
    'Number American Indian Alaska Native',
    'Number Asian',
    'Number Associations',
    'Number Below Poverty',
    'Number Black',
    'Number Chlamydia Cases',
    'Number Deaths',
    'Number Deaths 2',
    'Number Deaths 3',
    'Number Deaths 4',
    'Number Deaths 5',
    'Number Dentists',
    'Number Disabled',
    'Number Driving Deaths',
    'Number Drug Overdose Deaths',
    'Number Firearm Fatalities',
    'Number Food Insecure',
    'Number Hispanic',
    'Number Homeowners',
    'Number Households Cdc',
    'Number Households Chr',
    'Number Households With No Vehicle',
    'Number Households With Severe Cost Burden',
    'Number Housing Units',
    'Number Injury Deaths',
    'Number Institutionalized In Group Quarters',
    'Number Limited Access',
    'Number Limited English Abilities',
    'Number Minorities',
    'Number Mobile Homes',
    'Number Motor Vehicle Deaths',
    'Number Multi Unit Housing',
    'Number Native Hawaiian Other Pacific Islander',
    'Number No Highschool Diploma',
    'Number Non Hispanic White',
    'Number Not Proficient In English',
    'Number Overcrowding',
    'Number Primary Care Physicians',
    'Number Rural',
    'Number Single Parent Households Cdc',
    'Number Single Parent Households Chr',
    'Number Some College',
    'Number Unemployed Cdc',
    'Number Unemployed Chr',
    'Number Uninsured',
    'Number Uninsured 2',
    'Number Uninsured 3',
    'Number Workers Who Drive Alone',
    'Other Primary Care Provider Rate',
    'Overcrowding',
    'Percent 65 And Over',
    'Percent Adults With Diabetes',
    'Percent Adults With Obesity',
    'Percent Age 17 And Younger',
    'Percent Age 65 And Older',
    'Percent American Indian Alaska Native',
    'Percent Asian',
    'Percent Black',
    'Percent Children In Poverty',
    'Percent Disabled',
    'Percent Disconnected Youth',
    'Percent Drive Alone To Work',
    'Percent Driving Deaths With Alcohol Involvement',
    'Percent Enrolled In Free Or Reduced Lunch',
    'Percent Excessive Drinking',
    'Percent Female',
    'Percent Food Insecure',
    'Percent Hispanic',
    'Percent Homeowners',
    'Percent Institutionalized In Group Quarters',
    'Percent Insufficient Sleep',
    'Percent Less Than 18 Years Of Age',
    'Percent Limited Access To Healthy Foods',
    'Percent Limited English Abilities',
    'Percent Long Commute Drives Alone',
    'Percent Low Birthweight',
    'Percent Minorities',
    'Percent Mobile Homes',
    'Percent Multi Unit Housing',
    'Percent Native Hawaiian Other Pacific Islander',
    'Percent No Highschool Diploma',
    'Percent No Vehicle',
    'Percent Non Hispanic White',
    'Percent Not Proficient In English',
    'Percent Overcrowding',
    'Percent Physically Inactive',
    'Percent Rural',
    'Percent Severe Housing Cost Burden',
    'Percent Severe Housing Problems',
    'Percent Single Parent Households Cdc',
    'Percent Single Parent Households Chr',
    'Percent Some College',
    'Percent Unemployed Cdc',
    'Percent Unemployed Chr',
    'Percent Uninsured',
    'Percent Uninsured 2',
    'Percent Uninsured 3',
    'Percent Vaccinated',
    'Percent With Access To Exercise Opportunities',
    'Percent With Annual Mammogram',
    'Percentile Rank Age 17 And Younger',
    'Percentile Rank Age 65 And Older',
    'Percentile Rank Disabled',
    'Percentile Rank Household Comp Disability Theme',
    'Percentile Rank Housing And Transportation',
    'Percentile Rank Institutionalized In Group Quarters',
    'Percentile Rank Limited English Abilities',
    'Percentile Rank Minorities',
    'Percentile Rank Minority Status And Language Theme',
    'Percentile Rank Mobile Homes',
    'Percentile Rank Multi Unit Housing',
    'Percentile Rank No Vehicle',
    'Percentile Rank Overcrowding',
    'Percentile Rank Single Parent Households',
    'Percentile Rank Socioeconomic Theme',
    'Percentile Rank Unemployed',
    'Population',
    'Population 2',
    'Population Density Per Sqmi',
    'Presence Of Water Violation',
    'Preventable Hospitalization Rate',
    'Primary Care Physicians Rate',
    'Segregation Index',
    'Segregation Index 2',
    'Severe Housing Cost Burden',
    'Social Association Rate',
    'Suicide Rate Age Adjusted',
    'Teen Birth Rate',
    'Total Population',
    'Twentieth Percentile Income',
    'Violent Crime Rate',
    'Years Of Potential Life Lost Rate'
];